### ISSUE TITLE
Do you have discord bro?

### ISSUE THREAD

**Issue by iFanpSGTS** [rigel-star/plox#3]
add me on discord if u have, or send me ur username and tag, i want to discuss more about programming language with you

**Comment by rigel-star** [comment]
> add me on discord if u have, or send me ur username and tag, i want to discuss more about programming language with you

Contact me @ 0xrigelstar#3620

**Comment by iFanpSGTS** [comment]
> > add me on discord if u have, or send me ur username and tag, i want to discuss more about programming language with you
> 
> Contact me @ 0xrigelstar#3620

Accept, my discord name is iFanpS
